### ISSUE TITLE
AuthorizationTokenProducer doesn't accept Private-Token values

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#254]
`io.fabric8.launcher.base.identity.TokenIdentity#fromBearerAuthorizationHeader` does not accept `Authorization` headers with `Private-Token` instead of `Bearer`

See https://github.com/fabric8-launcher/launcher-backend/blob/0d339201fec12a846259b729f18f4e31f3468385/base/src/main/java/io/fabric8/launcher/base/identity/TokenIdentity.java#L27

**Comment by gastaldi** [comment]
Also, `Type.AUTHORIZATION` should be renamed to `Type.BEARER`, no?

**Comment by ia3andy** [comment]
> io.fabric8.launcher.base.identity.TokenIdentity#fromBearerAuthorizationHeader does not accept Authorization headers with Private-Token instead of Bearer

This is on purpose, I don't see why we would want any other type of authentication than "bearer" coming from the authorization header on the secured endpoints. 

For now, the only place were we build a private-token is in GitLab were we use `TokenIdentity.of(type, token)`. 

Thought by looking further, and maybe this why you sensed a problem a well, I think there is a problem with the fact of having the type in the TokenIdentity. KC is not returning the type of token, and it seems it is more depending on the service used that the token source itself.  We don't face this problem yet since we are only using GitHub

It would make more sense to remove the type from the TokenIdentity and let the service specify it instead.
- GitHub: UserPasswordIdentity or just the TokenIdentity (no type needed it uses a client)
- Bitbucket: UserPasswordIdentity (used as basic) or TokenIdentity (used as bearer)
- Gitlab: TokenIdentity (used as private-token)
- Osio clients: TokenIdentity (used as private-token)
- Openshift:  UserPasswordIdentity or just the TokenIdentity (no type needed it uses a client)
- KC: TokenIdentity (used as bearer)

**Comment by gastaldi** [comment]
Maybe it's easier to extract the type out of TokenIdentity and have two classes: `BearerTokenIdentity` and `PrivateTokenIdentity`? PrivateTokenIdentity could live inside the gitlab package since it's used only there

**Comment by gastaldi** [comment]
Closed in favor of https://github.com/fabric8-launcher/launcher-backend/issues/261
